### ISSUE TITLE
NPE when running on CI

### ISSUE THREAD

**Issue by purplefox** [vert-x3/vertx-http-service-factory#4]
https://vertx.ci.cloudbees.com/view/vert.x-3/job/vert.x3-http-service-factory/lastCompletedBuild/testReport/io.vertx.ext.httpservicefactory/DeploymentTest/testKeybaseIO/

**Comment by vietj** [comment]
One issue happens due to the HttpClientRequest#exceptionHandler that gets a VertxException thrown ClientConnection#handleClosed when the connection closes.

Is it an expected behavior to get such exception when connection closes ?

**Comment by purplefox** [comment]
It depends when the connection is closed.

If it's closed when a request/response is in progress, then yes.

**Comment by vietj** [comment]
there is this behavior in the test (with a plain http server), I will investigate more.

**Comment by vietj** [comment]
in practice how does one make the difference between let's say a connect error (that would prevent to connect and should be handled in the exceptionHandler) and a connection close that is expectable ?

Besides
- in a particular case I get the close reported on the exceptionHandler before the endHandler because the client code pauses the response
- however with no pause, the exceptionHandler is called on the response after the endHandler is called when the connection close, in that situation do we still consider that the request/response is in progress ?

**Comment by vietj** [comment]
please apologise for the confusion between request exception handle and response exception handler in the first paragraph.

however I'm still wondering, why vert.x reports the response close as response exception in both cases I outlined above.

**Comment by vietj** [comment]
it's fixed but I'm keeping open until I get clarification on my question.

**Comment by purplefox** [comment]
Ok, so the new behaviour was due to my fix for https://bugs.eclipse.org/bugs/show_bug.cgi?id=470228 in this pr: https://github.com/eclipse/vert.x/pull/1083

My reasoning was, because the connection was closed while the client was waiting for a response that's a protocol error and we must therefore flag it as an exception. But I could be wrong.

Maybe there is a better way of dealing with it. What behaviour would you suggest is correct?

We can change stuff if there is a better way.

**Comment by vietj** [comment]
I think that the connection exception should not be reported when it occurs in both case:
- after the end handler is called
- before the end handler is called but when it is paused (making sure that we received a correct full response from the server)

In both case, the connection was closed but the response is _ok_ and the client can process it fully.

**Comment by purplefox** [comment]
Julien-  are you referring to the end handler of the request or the response?

**Comment by vietj** [comment]
of the response.
